import type { AppConfig, FocusCheckIn, Project, QuickTask, RepeatingTask } from '../renderer/types';
interface ShortcutActionPayload {
    action: string;
    index?: number;
}
export declare const api: {
    getIsDev: () => Promise<any>;
    getAppData: () => Promise<any>;
    saveProject: (project: Project) => Promise<any>;
    deleteProject: (id: string) => Promise<any>;
    archiveProject: (id: string) => Promise<any>;
    unarchiveProject: (id: string) => Promise<any>;
    suspendProject: (id: string) => Promise<any>;
    unsuspendProject: (id: string) => Promise<any>;
    saveQuickNotes: (notes: string) => Promise<any>;
    saveConfig: (config: AppConfig) => Promise<any>;
    updateProjectTimer: (projectId: string, totalTimeMs: number, timerStartedAt: string | null) => Promise<any>;
    launchVscode: (path: string) => Promise<any>;
    launchIterm: (path: string) => Promise<any>;
    launchObsidian: (vault: string) => Promise<any>;
    launchBrowser: (url: string) => Promise<any>;
    enterFocusMode: () => Promise<any>;
    exitFocusMode: () => Promise<any>;
    getFocusUnsavedMs: () => Promise<any>;
    saveFocusCheckIn: (checkIn: FocusCheckIn) => Promise<any>;
    getFocusCheckIns: (taskId?: string) => Promise<any>;
    dismissCheckIn: () => Promise<any>;
    openStatsWindow: () => Promise<any>;
    openNewProjectWindow: () => Promise<any>;
    closeNewProjectWindow: () => Promise<any>;
    enterCompactMode: () => Promise<any>;
    exitCompactMode: () => Promise<any>;
    enterCleanView: () => Promise<any>;
    exitCleanView: () => Promise<any>;
    setTrafficLightsVisible: (visible: boolean) => Promise<any>;
    pickFolder: () => Promise<any>;
    pickObsidianNote: () => Promise<any>;
    saveQuickTask: (task: QuickTask) => Promise<any>;
    removeQuickTask: (id: string) => Promise<any>;
    completeQuickTask: (id: string) => Promise<any>;
    uncompleteQuickTask: (id: string) => Promise<any>;
    reorderQuickTasks: (orderedIds: string[]) => Promise<any>;
    reorderProjects: (orderedIds: string[]) => Promise<any>;
    reorderPinnedTasks: (updates: {
        projectId: string;
        taskId: string;
        order: number;
    }[]) => Promise<any>;
    toggleTaskToDoNext: (projectId: string, taskId: string) => Promise<any>;
    saveRepeatingTask: (task: RepeatingTask) => Promise<any>;
    removeRepeatingTask: (id: string) => Promise<any>;
    reorderRepeatingTasks: (orderedIds: string[]) => Promise<any>;
    acceptRepeatingProposal: (repeatingTaskId: string) => Promise<any>;
    dismissRepeatingProposal: (repeatingTaskId: string) => Promise<any>;
    onReloadData: (callback: () => void) => () => Electron.IpcRenderer;
    onShortcutAction: (callback: (data: ShortcutActionPayload) => void) => () => Electron.IpcRenderer;
    onCheckInCountdown: (callback: (remainingMs: number) => void) => () => Electron.IpcRenderer;
};
export {};
